### PR TITLE
fix(action): allow main ref when krew release bot action is triggered

### LINKED ISSUE #79: Krew GITHUB_REF failure
Hello, recently we have noticed in the K8sGPT release pipeline a new type of error from krew.
https://github.com/k8sgpt-ai/k8sgpt/actions/runs/11763964917/job/32768577152

To my knowledge we have not changed anything:

Error 
```
Digest: sha256:cb2a5cd92097ac4a92846833d7a9340d20ed247435fa447ccd3fef5499c65793
Status: Downloaded newer image for ghcr.io/rajatjindal/krew-release-bot:v0.0.46
time="2024-11-10T09:47:19Z" level=fatal msg="GITHUB_REF expected to be of format refs/tags/<tag> but found \"refs/heads/main\""
```

The ref is correct as we are releasing the main branch on a merge of the goreleaser PR set. 

Here is the .krew.yaml:
```
apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: gpt
spec:
  version: {{ .TagName }}
  homepage: https://github.com/k8sgpt-ai/k8sgpt
  shortDescription: "Giving Kubernetes Superpowers to everyone"
  description: |
    A tool for scanning your Kubernetes clusters, diagnosing, and triaging issues in simple English.
  platforms:
    ##########
    # Darwin #
    ##########
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{addURIAndSha "https://github.com/k8sgpt-ai/k8sgpt/releases/download/{{ .TagName }}/k8sgpt_Darwin_x86_64.tar.gz" .TagName | indent 6 }}
      files:
        - from: "k8sgpt"
          to: "kubectl-gpt"
        - from: "LICENSE"
          to: "."
      bin: kubectl-gpt
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      {{addURIAndSha "https://github.com/k8sgpt-ai/k8sgpt/releases/download/{{ .TagName }}/k8sgpt_Darwin_arm64.tar.gz" .TagName | indent 6 }}
      files:
        - from: "k8sgpt"
          to: "kubectl-gpt"
        - from: "LICENSE"
          to: "."
      bin: kubectl-gpt

    #########
    # Linux #
    #########
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      {{addURIAndSha "https://github.com/k8sgpt-ai/k8sgpt/releases/download/{{ .TagName }}/k8sgpt_Linux_x86_64.tar.gz" .TagName | indent 6 }}
      files:
        - from: "k8sgpt"
          to: "kubectl-gpt"
        - from: "LICENSE"
          to: "."
      bin: kubectl-gpt
    - selector:
        matchLabels:
          os: linux
          arch: arm64
      {{addURIAndSha "https://github.com/k8sgpt-ai/k8sgpt/releases/download/{{ .TagName }}/k8sgpt_Linux_arm64.tar.gz" .TagName | indent 6 }}
      files:
        - from: "k8sgpt"
          to: "kubectl-gpt"
        - from: "LICENSE"
          to: "."
      bin: kubectl-gpt
    - selector:
        matchLabels:
          os: linux
          arch: "386"
      {{addURIAndSha "https://github.com/k8sgpt-ai/k8sgpt/releases/download/{{ .TagName }}/k8sgpt_Linux_i386.tar.gz" .TagName | indent 6 }}
      files:
        - from: "k8sgpt"
          to: "kubectl-gpt"
        - from: "LICENSE"
          to: "."
      bin: kubectl-gpt

    ###########
    # Windows #
    ###########
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      {{addURIAndSha "https://github.com/k8sgpt-ai/k8sgpt/releases/download/{{ .TagName }}/k8sgpt_Windows_x86_64.zip" .TagName | indent 6 }}
      files:
        - from: "k8sgpt"
          to: "kubectl-gpt"
        - from: "LICENSE"
          to: "."
      bin: kubectl-gpt
    - selector:
        matchLabels:
          os: windows
          arch: arm64
      {{addURIAndSha "https://github.com/k8sgpt-ai/k8sgpt/releases/download/{{ .TagName }}/k8sgpt_Windows_arm64.zip" .TagName | indent 6 }}
      files:
        - from: "k8sgpt"
          to: "kubectl-gpt"
        - from: "LICENSE"
          to: "."
      bin: kubectl-gpt
    - selector:
        matchLabels:
          os: windows
          arch: "386"
      {{addURIAndSha "https://github.com/k8sgpt-ai/k8sgpt/releases/download/{{ .TagName }}/k8sgpt_Windows_i386.zip" .TagName | indent 6 }}
      files:
        - from: "k8sgpt"
          to: "kubectl-gpt"
        - from: "LICENSE"
          to: "."
      bin: kubectl-gpt
```

Help appreciated!

### PR DESCRIPTION
**Pull request by rajatjindal**
fixes #79

### CODE REVIEW

**Comment by rajatjindal** [comment]
Hi @RainbowMango

My understanding is that the krew-release-bot used to skip the pre-releases always (see [this](https://github.com/rajatjindal/krew-release-bot/blob/5991fda633ee3de129eb77ee5f5ac361ca07b51b/pkg/source/actions/action_runner.go#L59) from before this PR)

What I've fixed is that I moved the pre-release check to cicd.Provider interface. Earlier that check was outside cicd provider interface, so it would have failed if someone tried to run it from other providers workflow.

As part of this PR what I've also changed is to check if the release was triggered as part of push to main branch and no explicit tag is provided, then the bot check if the current commit for which this was triggered has a release associated with it, then it uses the tag from that release.

I hope that makes sense, pls feel free to reach out if you see any issues/concerns with that.

**Comment by RainbowMango** [comment]
Thanks for the clarification.  It makes sense to me.

What I'm asking is if there is a plan to skip the non-latest release. 
As you know, Krew only accepts the update from the latest release(or straightforward version bump). Otherwise, once we cut a new release, krew-release-bot would send a PR but it won't be accepted. [Like this one](https://github.com/kubernetes-sigs/krew-index/pull/4173).

PS:
It's not a problem for us now as we checked the release before involving `krew-release-bot`, only the latest release would send an update PR. 
This is probably a common issue for other projects, so I guess it might be enhanced from the action side.

**Comment by rajatjindal** [comment]
ah, it took me a second to realize what you mean by latest release here. skipping if it is not latest makes sense to me. could you please open an issue for it, I will think a bit more about it and update on that issue accordingly. 

thanks for using the bot.

**Comment by RainbowMango** [comment]
You can refer to this issue: https://github.com/rajatjindal/krew-release-bot/issues/75

**Pull request merged**
